{
 "title": "PowerStore Dashboard",
 "time": { "from": "now-12h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "group",
    "label": "Group",
    "query": {}
   },
   {
    "name": "cluster",
    "label": "Cluster",
    "query": {}
   },
   {
    "name": "appliance",
    "label": "Appliance",
    "query": {}
   }
  ]
 },
 "panels": [
  {
   "title": "Appliance Overview",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Appliance CPU",
   "type": "gauge",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance io_workload_cpu_utilization/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Data reduction",
   "type": "stat",
   "gridPos": { "h": 8, "w": 2, "x": 2, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* space metrics by appliance data_reduction/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Physical space usage",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 3, "x": 4, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "bits" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Free Physical Space" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* space metrics by appliance physical_free/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "true",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Used Physical Space" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* space metrics by appliance physical_used/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "true",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Number of volume",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of volume" },
     "itemTag": { "filter": "resource: volume" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Number of host",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of host" },
     "itemTag": { "filter": "resource: host" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Number of NAS Server",
   "type": "stat",
   "description": "Number of NAS Server",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of nas_server" },
     "itemTag": { "filter": "resource: nas_server" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Problem",
   "type": "alexanderzobnin-zabbix-triggers-panel",
   "gridPos": { "h": 8, "w": 11, "x": 13, "y": 1 },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$cluster" },
     "host": { "filter": "$host" },
     "item": { "filter": "" },
     "itemTag": { "filter": "/.*/" },
     "options": {
      "acknowledged": 2,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 0,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": {
      "acknowledged": 2,
      "count": true,
      "minSeverity": 3
     }
    }
   ]
  },
  {
   "title": "Model",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "/.*/" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "model" },
     "itemTag": { "filter": "resource: appliance" },
     "macro": { "filter": "" },
     "options": {
      "acknowledged": 2,
      "count": true,
      "disableDataAlignment": false,
      "hostProxy": false,
      "hostsInMaintenance": false,
      "limit": 1001,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "sortProblems": "default",
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "showProblems": "problems",
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Number of VG",
   "type": "stat",
   "description": "Number of volume group",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of volume_group" },
     "itemTag": { "filter": "resource: volume_group" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Number of HG",
   "type": "stat",
   "description": "Number of host group",
   "gridPos": { "h": 4, "w": 2, "x": 9, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of host_group" },
     "itemTag": { "filter": "resource: host_group" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Number of file system",
   "type": "stat",
   "description": "Number of file system",
   "gridPos": { "h": 4, "w": 2, "x": 11, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "application": { "filter": "" },
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": { "filter": "Number of file_system" },
     "itemTag": { "filter": "resource: file_system" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Appliance metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Appliance IOPS",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "iops" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:236",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Total IOPS" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance total_iops/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:257",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Read IOPS" ],
       "text": "setAlias(Appliance Read IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance read_iops/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:257",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Write IOPS" ],
       "text": "setAlias(Appliance Read IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance write_iops/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Appliance bandwidth",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "Bps" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Total IOPS" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance total_bandwidth/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Read IOPS" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance read_bandwidth/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Write IOPS" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance write_bandwidth/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Appliance latency",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "µs" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Avg Latency" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance avg_latency/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Avg Read Latency" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance avg_read_latency/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    },
    {
     "application": { "filter": "" },
     "functions": [
      {
       "$$hashKey": "object:1793",
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Appliance Avg Write Latency" ],
       "text": "setAlias(Appliance Total IOPS)"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.* performance metrics by appliance avg_write_latency/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": true,
      "disableDataAlignment": false,
      "minSeverity": 3,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" },
     "triggers": { "acknowledged": 2 }
    }
   ]
  },
  {
   "title": "Appliance Physical space",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "application": { "filter": "" },
     "functions": [
      {
       "added": true,
       "def": {
        "category": "Alias",
        "defaultParams": [],
        "name": "setAlias",
        "params": [
         { "name": "alias", "type": "string" }
        ]
       },
       "params": [ "Used space" ],
       "text": "setAlias()"
      }
     ],
     "group": { "filter": "$group" },
     "host": { "filter": "$appliance" },
     "item": {
      "filter": "/.*space metrics by appliance physical_used/"
     },
     "itemTag": { "filter": "metric: appliance" },
     "macro": { "filter": "" },
     "options": {
      "count": false,
      "disableDataAlignment": false,
      "showDisabledItems": false,
      "skipEmptyValues": false,
      "useTrends": "default",
      "useZabbixValueMapping": false
     },
     "proxy": { "filter": "" },
     "schema": 12,
     "table": {
      "skipEmptyValues": false
     },
     "tags": { "filter": "" },
     "trigger": { "filter": "" }
    }
   ]
  },
  {
   "title": "Node metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Node CPU",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:146",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "NodeA CPU" ],
         "text": "setAlias(NodeA CPU)"
        }
       ],
       "group": { "filter": "/.*/" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "N1 performance metrics by node io_workload_cpu_utilization"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "$$hashKey": "object:194",
         "def": {
          "category": "Alias",
          "defaultParams": [],
          "name": "setAlias",
          "params": [
           { "name": "alias", "type": "string" }
          ]
         },
         "params": [ "NodeB CPU" ],
         "text": "setAlias(NodeB CPU)"
        }
       ],
       "group": { "filter": "/.*/" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "N2 performance metrics by node io_workload_cpu_utilization"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Node bandwidth",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/N1 performance metrics by node (total|read|write)_bandwidth/"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/N2 performance metrics by node (total|read|write)_bandwidth/"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Node IOPS",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/N1 performance metrics by node (total|read|write)_iops/"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/N2 performance metrics by node (total|read|write)_iops/"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Node avg latency",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 35 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "N1 performance metrics by node avg_latency"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      },
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "N2 performance metrics by node avg_latency"
       },
       "itemTag": { "filter": "metric: node" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  },
  {
   "title": "Volume metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 27 },
   "collapsed": true,
   "panels": [
    {
     "title": "Volume free space bottom 5",
     "type": "bargauge",
     "description": "It will show as red if the free space less than 100GB",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "bottom",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "bottom(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*) space metrics by volume free/",
          "$1 free space"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.*space metrics by volume free/"
       },
       "itemTag": { "filter": "metric: volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Volume bandwidth top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 44 },
     "fieldConfig": { "defaults": { "unit": "binbps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by volume total_bandwidth/"
       },
       "itemTag": { "filter": "metric: volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Volume IOPS top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by volume total_iops/"
       },
       "itemTag": { "filter": "metric: volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "Volume latency top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 52 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*:(.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by volume avg_latency/"
       },
       "itemTag": { "filter": "metric: volume" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "NAS Server metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 28 },
   "collapsed": true,
   "panels": [
    {
     "title": "NAS Server bandwidth top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by nas server total_bandwidth/"
       },
       "itemTag": { "filter": "metric: nas_server" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "NAS Server IOPS top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 29 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by nas server total_iops/"
       },
       "itemTag": { "filter": "metric: nas_server" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "NAS Server avg latency top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 37 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by nas server avg_latency/"
       },
       "itemTag": { "filter": "metric: nas_server" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "File system metric",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 29 },
   "collapsed": true,
   "targets": [
    {}
   ],
   "panels": [
    {
     "title": "Volume free space bottom 5",
     "type": "bargauge",
     "description": "It will show as red if the free space less than 100GB",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "bits" } },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "bottom",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "bottom(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/(.*)/",
          "$1 free space"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.*space metrics by file system free/"
       },
       "itemTag": { "filter": "metric: file_system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "File system bandwidth top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 30 },
     "fieldConfig": { "defaults": { "unit": "Bps" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by file system total_bandwidth/"
       },
       "itemTag": { "filter": "metric: file_system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "File system IOPS top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "iops" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by file system total_iops/"
       },
       "itemTag": { "filter": "metric: file_system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    },
    {
     "title": "File system avg latency top 5",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 38 },
     "fieldConfig": { "defaults": { "unit": "µs" } },
     "targets": [
      {
       "application": { "filter": "" },
       "functions": [
        {
         "added": true,
         "def": {
          "category": "Filter",
          "defaultParams": [
           5,
           "avg"
          ],
          "name": "top",
          "params": [
           { "name": "number", "type": "int" },
           {
            "name": "value",
            "options": [
             "avg",
             "min",
             "max",
             "sum",
             "count",
             "median",
             "first",
             "last"
            ],
            "type": "string"
           }
          ]
         },
         "params": [
          "5",
          "avg"
         ],
         "text": "top(5, avg)"
        },
        {
         "added": true,
         "def": {
          "category": "Alias",
          "defaultParams": [
           "/(.*)/",
           "$1"
          ],
          "name": "replaceAlias",
          "params": [
           { "name": "regexp", "type": "string" },
           { "name": "newAlias", "type": "string" }
          ]
         },
         "params": [
          "/Discovered.*: (.*)/",
          "$1"
         ],
         "text": "replaceAlias(/(.*)/, $1)"
        }
       ],
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": {
        "filter": "/.* performance metrics by file system avg_latency/"
       },
       "itemTag": { "filter": "metric: file_system" },
       "macro": { "filter": "" },
       "options": {
        "count": true,
        "disableDataAlignment": false,
        "minSeverity": 3,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" },
       "triggers": { "acknowledged": 2 }
      }
     ]
    }
   ]
  },
  {
   "title": "Hardware",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 30 },
   "collapsed": true,
   "panels": [
    {
     "title": "Drive state",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 47 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": { "filter": "/State of Drive_.*/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    },
    {
     "title": "DIMM state",
     "type": "table",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 55 },
     "targets": [
      {
       "application": { "filter": "" },
       "group": { "filter": "$group" },
       "host": { "filter": "$appliance" },
       "item": { "filter": "/State of .*-DIMM.*/" },
       "itemTag": { "filter": "" },
       "macro": { "filter": "" },
       "options": {
        "count": false,
        "disableDataAlignment": false,
        "showDisabledItems": false,
        "skipEmptyValues": false,
        "useTrends": "default",
        "useZabbixValueMapping": false
       },
       "proxy": { "filter": "" },
       "schema": 12,
       "table": {
        "skipEmptyValues": false
       },
       "tags": { "filter": "" },
       "trigger": { "filter": "" }
      }
     ]
    }
   ]
  }
 ]
}